GET http://localhost:3000/usuarios/5

###

GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    
    "nombre": "",
    "apellido": "Osorio",
    "email": "mo6312454@gmail.com"
}