POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "mo6312454@gmail.com",
    "password": "martinospa123"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzMzOTQxNzg2LCJleHAiOjE3MzM5NDIwODZ9.9HyhKAsaxBp4sRFKjIKnldM6uwCehoYTKm3TCNLF__A